from myfunctions import*
from random import*
turtle.bgcolor("black")
turtle.tracer(False)
for times in range(4000):
    x = randint (-700, 700)
    y = randint (-700, 700)
    size = randint(1, 3)
    r = randint(0,255)
    g = randint(0,255)
    b = randint(0,255)
    c = (r,g,b)
    bob.color(c)
    jump(x,y)
    bob.begin_fill()
    square(size)
    bob.end_fill()
    
    
    
turtle.bgcolor("black")
bob.speed(0)
bob.color("orange")
jump(0,-100)
bob.begin_fill()
bob.circle(200)
bob.end_fill()

bob.penup()
bob.left(100)
bob.forward(300)
bob.pendown()
bob.color("white")
bob.begin_fill()
bob.circle(100)
bob.end_fill()
bob.color("black")
bob.penup()
bob.left(50)
bob.forward(100)
bob.pendown()
bob.begin_fill()
bob.circle(50)
bob.end_fill()
bob.color("white")
bob.penup()
bob.right(185)
bob.forward(270)
bob.pendown()
bob.begin_fill()
bob.circle(100)
bob.end_fill()
bob.color("black")
bob.penup()
bob.left(75)
bob.forward(135)
bob.pendown()
bob.begin_fill()
bob.circle(50)
bob.end_fill()

bob.left(180)
bob.penup()
bob.forward(340)
bob.pendown()
bob.begin_fill()
bob.right(90)
bob.forward(100)
bob.right(140)
bob.forward(100)
bob.left(12)
bob.forward(170)
bob.right(140)
bob.forward(100)
bob.right(30)
bob.forward(50)
bob.right(20)
bob.forward(95)
bob.end_fill()
bob.color("white")
bob.penup()
bob.right(50)
bob.forward(90)
bob.pendown()
bob.right(165)
bob.width(4)
bob.forward(60)
bob.left(80)
bob.forward(40)
bob.right(120)
bob.forward(60)
bob.left(140)
bob.forward(70)
bob.right(130)
bob.forward(75)
bob.left(135)
bob.forward(87)
bob.right(130)
bob.forward(45)
bob.left(102)
bob.forward(77)
bob.color("orange")
bob.penup()
bob.right(80)
bob.forward(52)
bob.pendown()
bob.forward(120)
bob.right(20)
bob.forward(120)
bob.right(10)
bob.forward(260)
bob.right(10)
bob.forward(140)
bob.penup()
bob.begin_fill()
bob.right(94)
bob.forward(750)
bob.right(95)
bob.pendown()
bob.forward(145)
bob.right(10)
bob.forward(260)
bob.right(10)
bob.forward(120)
bob.right(17)
bob.forward(140)
bob.end_fill()
bob.left(100)
bob.width(40)
bob.forward(400)
bob.width(5)
jump(-500,500)
bob.color("red")
bob.begin_fill()
bob.circle(220)
bob.end_fill()
jump(-470,150)
for times in range(9):
    bob.begin_fill()
    bob.color("orange")
    triangle(5)
    bob.end_fill()
    bob.color("red")
    bob.begin_fill()
    square(5)
    bob.end_fill()

bob.color("black")
jump(-660,-470)
bob.write("By Daniel Kong", font=("Arial", 39, "bold"), align="center")
jump(-656,-466)
bob.color("white")
bob.write("By Daniel Kong", font=("Arial", 39, "bold"), align="center")





